const express = require('express')
const router = express.Router()
const auth = require('./middleware/auth')

module.exports = app => {
    router.use('/tenants', require('./controllers/tenants'))
    router.use('/auth', auth.login)
    router.use('/benefits', auth.verifyAuthentication, require('./controllers/benefits'))
    router.use('/clients', auth.verifyAuthentication, require('./controllers/cliente'))
    router.use('/fiscal_conditions', auth.verifyAuthentication, require('./controllers/condicionfiscal'))
    router.use('/current_accounts', auth.verifyAuthentication, require('./controllers/cuentacorriente'))
    router.use('/daily_business_statistics', auth.verifyAuthentication, require('./controllers/dailyBusinessStatistics'))
    router.use('/documents', auth.verifyAuthentication, require('./controllers/documento'))
    router.use('/business', auth.verifyAuthentication, require('./controllers/empresa'))
    router.use('/entries', auth.verifyAuthentication, require('./controllers/entrada'))
    router.use('/generics', auth.verifyAuthentication, require('./controllers/genericos'))
    router.use('/interface_styles', auth.verifyAuthentication, require('./controllers/interfaceStyles'))
    router.use('/brands', auth.verifyAuthentication, require('./controllers/marca'))
    router.use('/payment_methods', auth.verifyAuthentication, require('./controllers/mediopago'))
    router.use('/products', auth.verifyAuthentication, require('./controllers/producto'))
    router.use('/sale_points', auth.verifyAuthentication, require('./controllers/puntoventa'))
    router.use('/types', auth.verifyAuthentication, require('./controllers/rubro'))
    router.use('/outputs', auth.verifyAuthentication, require('./controllers/salida'))
    router.use('/seed', auth.verifyAuthentication, require('./controllers/seed'))
    router.use('/stock_history', auth.verifyAuthentication, require('./controllers/stockHistory'))
    router.use('/measure_units', auth.verifyAuthentication, require('./controllers/unidadmedida'))
    router.use('/uploads', auth.verifyAuthentication, require('./controllers/uploader'))
    router.use('/users', auth.verifyAuthentication, require('./controllers/usuario'))
    router.use('/sales', auth.verifyAuthentication, require('./controllers/venta'))
    router.use('/sales_areas', auth.verifyAuthentication, require('./controllers/zonadeventa'))
    app.use('/api/v1/', router)
}