const express = require('express')
const router = express.Router()
const auth = require('./middleware/auth')

module.exports = app => {
    router.use('/auth', auth.login)
    router.use('/clientes', auth.verifyAuthentication, require('./controllers/cliente'))
    router.use('/condicionesfiscales', auth.verifyAuthentication, require('./controllers/condicionfiscal'))
    router.use('/cuentacorriente', auth.verifyAuthentication, require('./controllers/cuentacorriente'))
    router.use('/daily_business_statistics', auth.verifyAuthentication, require('./controllers/dailyBusinessStatistics'))
    router.use('/documentos', auth.verifyAuthentication, require('./controllers/documento'))
    router.use('/empresas', auth.verifyAuthentication, require('./controllers/empresa'))
    router.use('/entradas', auth.verifyAuthentication, require('./controllers/entrada'))
    router.use('/fiscalNotes', auth.verifyAuthentication, require('./controllers/fiscalNote'))
    router.use('/genericos', auth.verifyAuthentication, require('./controllers/genericos'))
    router.use('/marcas', auth.verifyAuthentication, require('./controllers/marca'))
    router.use('/mediospago', auth.verifyAuthentication, require('./controllers/mediopago'))
    router.use('/productos', auth.verifyAuthentication, require('./controllers/producto'))
    router.use('/puntosventa', auth.verifyAuthentication, require('./controllers/puntoventa'))
    router.use('/rubros', auth.verifyAuthentication, require('./controllers/rubro'))
    router.use('/salidas', auth.verifyAuthentication, require('./controllers/salida'))
    router.use('/stock_history', auth.verifyAuthentication, require('./controllers/stockHistory'))
    router.use('/unidadesmedida', auth.verifyAuthentication, require('./controllers/unidadmedida'))
    router.use('/uploads', auth.verifyAuthentication, require('./controllers/uploader'))
    router.use('/usuarios', auth.verifyAuthentication, require('./controllers/usuario'))
    router.use('/ventas', auth.verifyAuthentication, require('./controllers/venta'))
    router.use('/zonasdeventas', auth.verifyAuthentication, require('./controllers/zonadeventa'))
    app.use('/api/v1/', router)
}